# Form implementation generated from reading ui file 'studentperformance.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 672)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnInsert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsert.setGeometry(QtCore.QRect(280, 290, 121, 41))
        self.btnInsert.setObjectName("btnInsert")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(450, 290, 121, 41))
        self.btnDisplay.setObjectName("btnDisplay")
        self.txtId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtId.setGeometry(QtCore.QRect(440, 80, 113, 22))
        self.txtId.setObjectName("txtId")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(440, 130, 113, 22))
        self.txtName.setObjectName("txtName")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(440, 180, 113, 22))
        self.txtScore.setObjectName("txtScore")
        self.lblId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblId.setGeometry(QtCore.QRect(300, 80, 111, 31))
        self.lblId.setObjectName("lblId")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(300, 180, 121, 31))
        self.lblScore.setObjectName("lblScore")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(300, 130, 111, 31))
        self.lblName.setObjectName("lblName")
        self.studentTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.studentTableWidget.setGeometry(QtCore.QRect(320, 370, 256, 192))
        self.studentTableWidget.setObjectName("studentTableWidget")
        self.studentTableWidget.setColumnCount(0)
        self.studentTableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.connection = self.createdbconnection()
        self.btnInsert.clicked.connect(self.insert_data)
        self.btnDisplay.clicked.connect(self.display_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnInsert.setText(_translate("MainWindow", "Insert Data"))
        self.btnDisplay.setText(_translate("MainWindow", "Display Data"))
        self.lblId.setText(_translate("MainWindow", "Enter Student ID"))
        self.lblScore.setText(_translate("MainWindow", "Enter Student Score"))
        self.lblName.setText(_translate("MainWindow", "Enter Student Name"))

    def createdbconnection(self):
        try:
            connection = mdb.connect(
                host="localhost",
                user="newuser",
                password="newuser",
                database="studentperformacedb"
            )
            print("connected to DB")
            return connection
        except Exception as e:
            print("Error connecting to DB")
            print(e)
            return None
            
    def insert_data(self):
        try:
            student_id =self.txtId.text()
            student_name = self.txtName.text()
            student_score= self.txtScore.text()           
            cursor = self.connection.cursor()
            cursor.execute("insert into student performance (studentid, studentname, studentscore) values (%s, %s, %s)", [student_id,student_name,student_score])
            self.connection.commit()
            print("Added data to the table")
        except Exception as e:
            print("Error inserting data")
            print(e)
            
    def display_data(self):
        try:
            cursor = self.connection.cursor()
            cursor.execute("select * from studentperformance")
            results = cursor.fetchall()
            row_count = len(results)
            column_count = len(cursor.description)
            print(results)
            print(cursor.description)
            
        except Exception as e:
            print(e)
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
