# Form implementation generated from reading ui file 'fruitpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 694)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(40, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblFruit.setFont(font)
        self.lblFruit.setObjectName("lblFruit")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(40, 160, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblQuantity.setFont(font)
        self.lblQuantity.setObjectName("lblQuantity")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(40, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.cmbFruit.setFont(font)
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(190, 160, 113, 25))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(50, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(40, 300, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblCost.setFont(font)
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(190, 300, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtCost.setFont(font)
        self.txtCost.setObjectName("txtCost")
        self.lblPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPrice.setGeometry(QtCore.QRect(190, 120, 311, 31))
        self.lblPrice.setText("")
        self.lblPrice.setObjectName("lblPrice")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.fruit_price = {"Apple": 2.50, "Banana": 1.25, "Orange": 3.30, "Grapes": 4.20, "Mango": 3.75}
        
        self.cmbFruit.currentIndexChanged.connect(self.display_price)
        
        self.btnCalculate.clicked.connect(self.calculate_cost)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblFruit.setText(_translate("MainWindow", "Select a fruit"))
        self.lblQuantity.setText(_translate("MainWindow", "Enter Quantity"))
        self.cmbFruit.setItemText(0, _translate("MainWindow", "Select a fruit"))
        self.cmbFruit.setItemText(1, _translate("MainWindow", "Apple"))
        self.cmbFruit.setItemText(2, _translate("MainWindow", "Banana"))
        self.cmbFruit.setItemText(3, _translate("MainWindow", "Orange"))
        self.cmbFruit.setItemText(4, _translate("MainWindow", "Grapes"))
        self.cmbFruit.setItemText(5, _translate("MainWindow", "Mango"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate"))
        self.lblCost.setText(_translate("MainWindow", "Total Cost"))

    def display_price(self):
        selected_fruit = self.cmbFruit.currentText()
        price_of_fruit = self.fruit_price.get(selected_fruit)
        self.lblPrice.setText("Price per pound: " + str(price_of_fruit))
        
    def calculate_cost(self):
        #To do: add validation
        
        quantity = int(self.txtQuantity.text())
        selected_fruit = self.cmbFruit.currentText()
        if(selected_fruit in self.fruit_price.keys()):
            price_of_fruit = self.fruit_price.get(selected_fruit)
            cost_of_purchase = round(quantity * price_of_fruit , 2)
            self.txtCost.setText(str(cost_of_purchase))
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Fruit Purchase")
            msg.setText("Select a fruit")
            self.lblPrice.setText("" )
            msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
