# Form implementation generated from reading ui file 'evenorodd.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 614)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtNumber = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtNumber.setGeometry(QtCore.QRect(290, 120, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtNumber.setFont(font)
        self.txtNumber.setObjectName("txtNumber")
        self.lblNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumber.setGeometry(QtCore.QRect(170, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblNumber.setFont(font)
        self.lblNumber.setObjectName("lblNumber")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(170, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(290, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtResult.setFont(font)
        self.txtResult.setObjectName("txtResult")
        self.btnCheck = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCheck.setGeometry(QtCore.QRect(310, 180, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCheck.setFont(font)
        self.btnCheck.setObjectName("btnCheck")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #Event: Execute function evenoroddcheck when the check button is clicked
        self.btnCheck.clicked.connect(self.evenoroddcheck)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblNumber.setText(_translate("MainWindow", "Enter a number"))
        self.lblResult.setText(_translate("MainWindow", "Result"))
        self.btnCheck.setText(_translate("MainWindow", "Check"))

    def evenoroddcheck(self):
        # Get the value entered by the user and store in input_number
        input_number = self.txtNumber.toPlainText()
        if(input_number.isdigit()):
        
            input_number = int(input_number)
            if(input_number%2 == 0):
                self.txtResult.setText("Number is even")
            else:
                self.txtResult.setText("Number is odd")
        else:
            #create a new MessageBox instance
            msg = QMessageBox()
            msg.setText("Please enter a valid number")
            msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
