# Form implementation generated from reading ui file 'financialplanner.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 785)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAnnualAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAnnualAmount.setGeometry(QtCore.QRect(40, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAnnualAmount.setFont(font)
        self.lblAnnualAmount.setObjectName("lblAnnualAmount")
        self.txtAnnualAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAnnualAmount.setGeometry(QtCore.QRect(240, 100, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtAnnualAmount.setFont(font)
        self.txtAnnualAmount.setObjectName("txtAnnualAmount")
        self.lblTotalTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotalTime.setGeometry(QtCore.QRect(40, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblTotalTime.setFont(font)
        self.lblTotalTime.setObjectName("lblTotalTime")
        self.txtTotalTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotalTime.setGeometry(QtCore.QRect(240, 160, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtTotalTime.setFont(font)
        self.txtTotalTime.setObjectName("txtTotalTime")
        self.lstOutput = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstOutput.setGeometry(QtCore.QRect(460, 180, 256, 381))
        self.lstOutput.setObjectName("lstOutput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(490, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblOutput.setFont(font)
        self.lblOutput.setObjectName("lblOutput")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(250, 260, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.chkPlan = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chkPlan.setGeometry(QtCore.QRect(260, 210, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.chkPlan.setFont(font)
        self.chkPlan.setObjectName("chkPlan")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(130, 420, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(300, 420, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btnCalculate.clicked.connect(self.calculate)
        self.btnClear.clicked.connect(self.clear)
        self.btnExit.clicked.connect(self.exit_application)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblAnnualAmount.setText(_translate("MainWindow", "Enter Annual Amount"))
        self.lblTotalTime.setText(_translate("MainWindow", "Enter Total Time"))
        self.lblOutput.setText(_translate("MainWindow", "Portfolio Value"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate"))
        self.chkPlan.setText(_translate("MainWindow", "Plan 2040"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))

    def calculate(self):
        annual_amount = self.txtAnnualAmount.text()
        total_time = self.txtTotalTime.text()
        current_portfolio_value = 0
        years = 0
        
        if(annual_amount.isdigit() and total_time.isdigit()):
            annual_amount = int(annual_amount)
            total_time = int(total_time)
            
            if(self.chkPlan.isChecked):
                rate = 7.0
            else:
                rate = 5.0
                
            for each_year in range(0, total_time):
                current_portfolio_value = (current_portfolio_value + annual_amount) * (1 + rate/100)
                years = years + 1
                currency = f"${current_portfolio_value:,.2f}"
                self.lstOutput.addItem(str(years) + "     " + currency)
                
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Financial Planner")
            msg.setText("Please enter valid inputs for annual amount and time taken")
            msg.exec()
            
    def clear(self):
        #Will clear Annual Amount text box
        self.txtAnnualAmount.clear()
        #Will clear Total Time text box
        self.txtTotalTime.clear()
        #Will uncheck the checkbox
        self.chkPlan.setChecked(False)
        #Will clear the list box
        self.lstOutput.clear()
    
    def exit_application(self):
        QtWidgets.QApplication.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
